insert into makes (name) values ('Acura');
insert into makes (name) values ('Advance Mixer');
insert into makes (name) values ('Alfa Romeo');
insert into makes (name) values ('AM General');
insert into makes (name) values ('American LaFrance');
insert into makes (name) values ('American Motors');
insert into makes (name) values ('Aprilia Motorcycle');
insert into makes (name) values ('Arctic Cat');
insert into makes (name) values ('Aston Martin');
insert into makes (name) values ('Asuna');
insert into makes (name) values ('Audi');
insert into makes (name) values ('Austin');
insert into makes (name) values ('Austin Healey');
insert into makes (name) values ('Autocar');
insert into makes (name) values ('Avanti');
insert into makes (name) values ('Bajaj Motorcycle');
insert into makes (name) values ('Bentley');
insert into makes (name) values ('Bering');
insert into makes (name) values ('Bertone');
insert into makes (name) values ('BMW');
insert into makes (name) values ('BMW Motorcycle');
insert into makes (name) values ('Bricklin');
insert into makes (name) values ('Buell Motorcycle');
insert into makes (name) values ('Bugatti');
insert into makes (name) values ('Buick');
insert into makes (name) values ('Cadillac');
insert into makes (name) values ('Can-Am Motorcycle');
insert into makes (name) values ('Capacity Of Texas');
insert into makes (name) values ('Chevrolet');
insert into makes (name) values ('Chrysler');
insert into makes (name) values ('Citroen');
insert into makes (name) values ('Daewoo');
insert into makes (name) values ('Daihatsu');
insert into makes (name) values ('DeLorean');
insert into makes (name) values ('Diamond Reo');
insert into makes (name) values ('Dodge');
insert into makes (name) values ('Ducati Motorcycle');
insert into makes (name) values ('Eagle');
insert into makes (name) values ('Edsel');
insert into makes (name) values ('Ferrari');
insert into makes (name) values ('Fiat');
insert into makes (name) values ('Fisker');
insert into makes (name) values ('Ford');
insert into makes (name) values ('Freightliner');
insert into makes (name) values ('Gas Gas Motorcycle');
insert into makes (name) values ('Genesis');
insert into makes (name) values ('Geo');
insert into makes (name) values ('Giant');
insert into makes (name) values ('GMC');
insert into makes (name) values ('Harley Davidson Motorcycle');
insert into makes (name) values ('Hino');
insert into makes (name) values ('Honda');
insert into makes (name) values ('Honda Motorcycle');
insert into makes (name) values ('Hummer');
insert into makes (name) values ('Husqvarna Motorcycle');
insert into makes (name) values ('Hyosung Motorcycle');
insert into makes (name) values ('Hyundai');
insert into makes (name) values ('Indian Motorcycle');
insert into makes (name) values ('Indiana Phoenix');
insert into makes (name) values ('Infiniti');
insert into makes (name) values ('International');
insert into makes (name) values ('Isuzu');
insert into makes (name) values ('Iveco');
insert into makes (name) values ('Jaguar');
insert into makes (name) values ('Jeep');
insert into makes (name) values ('Kalmar');
insert into makes (name) values ('Kawasaki Motorcycle');
insert into makes (name) values ('Kenworth');
insert into makes (name) values ('Kia');
insert into makes (name) values ('Kovatch');
insert into makes (name) values ('KTM Motorcycle');
insert into makes (name) values ('Lada');
insert into makes (name) values ('Lamborghini');
insert into makes (name) values ('Land Rover');
insert into makes (name) values ('Lexus');
insert into makes (name) values ('Lincoln');
insert into makes (name) values ('Mack');
insert into makes (name) values ('Maserati');
insert into makes (name) values ('Maybach');
insert into makes (name) values ('Mazda');
insert into makes (name) values ('Mercedes-Benz');
insert into makes (name) values ('Mercury');
insert into makes (name) values ('Merkur');
insert into makes (name) values ('MG');
insert into makes (name) values ('Mini');
insert into makes (name) values ('Mitsubishi');
insert into makes (name) values ('Mitsubishi Fuso');
insert into makes (name) values ('Mobility Ventures');
insert into makes (name) values ('Moto Guzzi Motorcycle');
insert into makes (name) values ('Nissan');
insert into makes (name) values ('Oldsmobile');
insert into makes (name) values ('Opel');
insert into makes (name) values ('Peterbilt');
insert into makes (name) values ('Peugeot');
insert into makes (name) values ('Piaggio Motorcycle');
insert into makes (name) values ('Plymouth');
insert into makes (name) values ('Polaris');
insert into makes (name) values ('Polaris Motorcycle');
insert into makes (name) values ('Pontiac');
insert into makes (name) values ('Porsche');
insert into makes (name) values ('Ram');
insert into makes (name) values ('Renault');
insert into makes (name) values ('Rolls-Royce');
insert into makes (name) values ('Rover');
insert into makes (name) values ('Saab');
insert into makes (name) values ('Saturn');
insert into makes (name) values ('Seat');
insert into makes (name) values ('Scion');
insert into makes (name) values ('Seagrave Fire Apparatus');
insert into makes (name) values ('Simca');
insert into makes (name) values ('Ski-Doo');
insert into makes (name) values ('Smart');
insert into makes (name) values ('SRT');
insert into makes (name) values ('Sterling');
insert into makes (name) values ('Studebaker');
insert into makes (name) values ('Subaru');
insert into makes (name) values ('Sunbeam');
insert into makes (name) values ('Suzuki');
insert into makes (name) values ('Suzuki Motorcycle');
insert into makes (name) values ('Terex / Terex Advance');
insert into makes (name) values ('Tesla');
insert into makes (name) values ('Think');
insert into makes (name) values ('Toyota');
insert into makes (name) values ('Triumph');
insert into makes (name) values ('Triumph Motorcycle');
insert into makes (name) values ('UD');
insert into makes (name) values ('Vespa Motorcycle');
insert into makes (name) values ('Victory Motorcycle');
insert into makes (name) values ('Volkswagen');
insert into makes (name) values ('Volvo');
insert into makes (name) values ('VPG');
insert into makes (name) values ('White/GMC');
insert into makes (name) values ('Yamaha');
insert into makes (name) values ('Yamaha Motorcycle');
insert into makes (name) values ('Yugo');
insert into makes (name) values ('ZERO Motorcycle');